### ISSUE TITLE
cat command instead of git status

### ISSUE THREAD

**Issue by pedroteixeira** [Potherca/git-split-file#7]
Probably should be `$(git status` instead of `$(cat git status` at:
https://github.com/potherca-bash/git-split-file/blob/master/src/git-split-file.sh#L374

**Comment by pedroteixeira** [comment]
I just tried to use the script and I had conflicts when splitting to 4 files. Perhaps `git add -A :/` to add all files?

I changed to it in order to make the script add the files and it seemed to have worked :+1:

**Comment by Potherca** [comment]
> Probably should be `$(git status` instead of `$(cat git status`

Yup. That's a bug. Will fix.

> Perhaps git add -A to add all files?

I'd have to see if/what conflicts that might create with other use-cases but that might be a good idea :+1:
